networks:
  syncthing4swarm:
    driver: overlay
    internal: true

services:
  syncthing4swarm:
    image: syncthing4swarm/syncthing4swarm:latest
    volumes:
      - /var/syncthing:/var/syncthing
    deploy:
      mode: global
    environment:
      - STGUIAPIKEY=A1B2C3 # CHANGE ME
      - SYNCTHING_PORT=8384
      - SYNCTHING_FOLDER_PATH=/var/syncthing/data
      - PUID=0
      - PGID=0
    networks:
      - syncthing4swarm
